name: bdk_wallet_kit_example
description: Example Flutter app for bdk_wallet_kit.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  bdk_wallet_kit:
    path: ..
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
